#index:
#    path: /
#    controller: App\Controller\DefaultController::index

restapi:
  prefix: /rest/api
  resource: '../src/Controller'

articles:
  type: rest
  resource: App\Controller\ArticlesController